project_id = "fexafkqzpbzjcupvbfhe"

[functions.shopify-sync-pages]
verify_jwt = false

[functions.shopify-sync-blog-posts]
verify_jwt = false

[functions.shopify-customers-count]
verify_jwt = false

[functions.shopify-orders-count]
verify_jwt = false

[functions.shopify-sync-customers-batch]
verify_jwt = false

[functions.shopify-sync-abandoned-checkouts]
verify_jwt = false

[functions.shopify-test]
verify_jwt = false

[functions.shopify-sync]
verify_jwt = false

[functions.shopify-sync-batch]
verify_jwt = false

[functions.shopify-sync-collections]
verify_jwt = false

[functions.shopify-sync-orders]
verify_jwt = false

[functions.shopify-sync-orders-batch]
verify_jwt = false

[functions.migrate-images-to-storage]
verify_jwt = false

[functions.shopify-sync-product-collections]
verify_jwt = false

[functions.generate-pet-image]
verify_jwt = false
