project_id = "fexafkqzpbzjcupvbfhe"

[functions.shopify-sync-pages]
verify_jwt = false

[functions.shopify-sync-blog-posts]
verify_jwt = false

[functions.shopify-sync-customers-batch]
verify_jwt = false

[functions.shopify-sync-abandoned-checkouts]
verify_jwt = false

[functions.shopify-sync-batch]
verify_jwt = false

[functions.shopify-sync-collections]
verify_jwt = false

[functions.shopify-sync-orders-batch]
verify_jwt = false

[functions.migrate-images-to-storage]
verify_jwt = false

[functions.shopify-sync-product-collections]
verify_jwt = false

[functions.generate-pet-image]
verify_jwt = false

[functions.shopify-sync-option-names]
verify_jwt = false

[functions.sapo-sync-inventory]
verify_jwt = false

[functions.ga4-analytics]
verify_jwt = false

[functions.track-order]
verify_jwt = false

[functions.shopify-sync-brands]
verify_jwt = false

[functions.seed-navigation-menus]
verify_jwt = false
